name: PyTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}

jobs:
  check:
    outputs:
      status: ${{ steps.check_env_file.outputs.files_exists }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check Enc Env file existence
        id: check_env_file
        uses: andstor/file-existence-action@v2
        with:
          files: "env/.env.${{ github.ref_name }}.enc"

  test:
    name: Test
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.status == 'true'
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    # Decrypt Encrypted Env file
    - name: Load env
      run: |
        python setup/load_env.py "env/.env.${{ github.ref_name }}.enc"

    # Load .env file
    - name: Load .env file
      uses: xom9ikk/dotenv@v1.0.2
      with:
        path: ./
    - name: Setup Project
      run: |
        bash scripts/init.sh
    - name: Run Tests
      run: |
        bash scripts/test.sh
